### ISSUE TITLE
How to check/uncheck with JavaScript

### ISSUE THREAD

**Issue by luchebert** [maxweldsouza/font-awesome-controls#3]
Hi there, I just started using these checkboxes which look great.  I do have some functionality on my site that allows users to check/uncheck all in a multiselect.  Is there a way to check/uncheck these font awesome controls with JavaScript?

Thanks!

**Comment by maxweldsouza** [comment]
It's like any regular checkbox.
https://stackoverflow.com/questions/8206565/check-uncheck-checkbox-with-javascript
